config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  get "welcome/index"

  root 'welcome#index'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyDesign</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice" style="<%="display:none;" if notice.nil? %>"><%= notice %></p>
  <p class="alert" style="<%="display:none;" if alert.nil? %>"><%= alert %></p>
  <header>

    <!-- Navigation -->

    <nav class="navbar navbar-custom navbar-fixed-top nav-color" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                   <span class="logo-nav">GU&Iacute;A </span> <strong class="text-nav"> 360</strong>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->

            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                  <li class="hidden">
                      <a href="#page-top"></a>
                  </li>
                  <li><%= link_to "Inicio", root_path %></li>
                  <% if usuario_signed_in?  %>
                    <li><%= link_to "Editar Perfil", edit_usuario_registration_path(current_usuario) %></li>
                    <li><%= link_to "Cerrar sesión", destroy_usuario_session_path, method: :delete %></li>
                  <%else%>
                    <li><%= link_to "Ingresar", new_usuario_session_path  %></li>
                    <li><%= link_to "Registrarse", new_usuario_registration_path  %></li>
                  <%end%>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

  </header>
  <div class="container">
    <div class="row">
        <div class=".col-xs-12"><%= yield %></div>
          <div class=".col-xs-3">
            <h2>About Us</h2>
          </div>
    </div>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container-fluid">

  <div class="header">
    <h2 class="logo">Jair Manosalva</h2>
    <h1>This app is the next big thing.</h1>
  </div>
  <div class="teaser">

    <p class="stress">FIND A PLACE YOU WANT !  MAKE A RESERVATION ! WE ARE MAKE A EXPERIENCE TRAVELING PLACES ON 360 VIEW !.</p>

  <!-- Begin MailChimp Signup Form -->
  <!-- Note: You'll want to replace the form action and the input name with values from your own MailChimp account -->
    <div class="mailchimp" id="mc_embed_signup">
      <form class="navbar-form navbar-left" role="search" id="mc-embedded-subscribe-form">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-danger">Submit</button>
      </form>
    </div><br>
    <!--End mc_embed_signup-->
    <hr class="launchrocket social">
    <div class="social">
      <h4> Follow us for updates:
        <a href="#" target="_blank">
          <i class="fa fa-facebook"></i>
        </a>
        <a href="#" target="_blank">
          <i class="fa fa-twitter"></i>
        </a>
        <a href="#" target="_blank">
          <i class="fa fa-google-plus"></i>
        </a>
      </h4>
    </div>
  </div>
  <%= video_tag "bg.mp4", :id =>'bgvid', :controls => 'autoplay' %>

</div>
</body>